# flake8: NOQA
# do not edit this file. seriously, do not edit this file.
try:
    __import__("pkg_resources").declare_namespace(__name__)
except ImportError:
    from pkgutil import extend_path

    __path__ = extend_path(__path__, __name__)
import modulefinder

for p in __path__:
    modulefinder.AddPackagePath(__name__, p)
